AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dev-sam stack

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Architectures:
      - x86_64

Resources:

  # API Gateway HTTP API
  DevSamRagAppHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: dev-sam-rag-app-http-api
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE

  # Lambda
  DevSamRagPromptImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-rag-prompt-images-function
      CodeUri: functions/rag-prompt-images/
      Handler: index.handler
      Runtime: nodejs22.x
      Events:
        PresignedUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /presigned-url
            Method: POST

  DevSamS3ImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-s3-images-function
      CodeUri: functions/s3-images/
      Handler: index.handler
      Runtime: nodejs22.x
      Events:
        GetImage:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /get-image
            Method: POST

  DevSamCognitoPostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-cognito-post-confirmation-function
      CodeUri: functions/cognito-post-confirmation/
      Handler: index.handler
      Runtime: nodejs22.x

  DevSamCognitoUserEnableFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-cognito-user-enable-function
      CodeUri: functions/cognito-user-enable/
      Handler: index.handler
      Runtime: nodejs22.x

  DevSamRagGenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-rag-generate-image-function
      CodeUri: functions/rag-generate-image/
      Handler: index.handler
      Runtime: nodejs22.x

  DevSamRagGetChatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-rag-get-chats-function
      CodeUri: functions/rag-get-chats/
      Handler: app.lambda_handler
      Runtime: python3.13
      Events:
        GetChats:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /chats
            Method: GET

  DevSamSearchChatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-search-chats-function
      CodeUri: functions/search-chats/
      Handler: index.handler
      Runtime: nodejs22.x
      Events:
        GETSearch:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /search
            Method: GET

  DevSamRagSseStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-rag-sse-stream-function
      CodeUri: functions/rag-sse-stream/
      Handler: index.handler
      Runtime: nodejs22.x

  DevSamRagGetChatDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-sam-rag-get-chat-detail-function
      CodeUri: functions/rag-get-chat-detail/
      Handler: app.lambda_handler
      Runtime: python3.13
      Events:
        GetChatDetail:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /chats/{chatId}
            Method: GET

        DeleteChatDetail:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevSamRagAppHttpApi
            Path: /chats/{chatId}
            Method: DELETE

  # DynamoDB
  DevSamRagAppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dev-sam-rag-app-table
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST