AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ragchat stack

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Architectures:
      - x86_64
    Tags:
      Project: ragchat-app
      ManagedBy: sam
      Environment: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name (dev/stg/prod)
  DomainName:
    Type: String
    Default: dev.ai.cpinfo.jp
    Description: Domain name for CloudFront distribution
  CertificateArn:
    Type: String
    Description: ACM certificate ARN for the domain (must be in us-east-1)
    Default: "arn:aws:acm:us-east-1:794038219704:certificate/7d2d02e3-c835-491a-b616-50b55f738943"

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, ""]]

Resources:

  # IAMロールスタック（ネストスタック）
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam-roles.yaml
      Parameters:
        Environment: !Ref Environment
        DynamoDBTableArn: !GetAtt RagChatTable.Arn
        CognitoUserPoolArn: !GetAtt RagChatUserPool.Arn

  # API Gateway HTTP API
  RagChatHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${Environment}-ragchat-http-api"
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${RagChatUserPool}"
              audience:
                - !Ref RagChatUserPoolClient
            IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: CognitoAuthorizer


  # Lambda Functions
  RagChatPromptImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-prompt-images-function"
      CodeUri: functions/rag-prompt-images/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaPromptImagesRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref RagChatPromptImagesBucket
      Events:
        PresignedUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /presigned-url
            Method: POST

  RagChatS3ImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-s3-images-function"
      CodeUri: functions/s3-images/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaS3ImagesRoleArn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref RagChatPromptImagesBucket
      Events:
        GetImage:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /get-image
            Method: POST

  RagChatCognitoPostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-cognito-post-confirmation-function"
      CodeUri: functions/cognito-post-confirmation/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaCognitoSESRoleArn

  RagChatCognitoUserEnableFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-cognito-user-enable-function"
      CodeUri: functions/cognito-user-enable/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaCognitoSESRoleArn

  RagChatGenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-generate-image-function"
      CodeUri: functions/rag-generate-image/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaGenerateRoleArn
      Environment:
        Variables:
          BEDROCK_GENIMAGE_AWS_REGION: us-east-1
          DYNAMODB_TABLE_NAME: !Ref RagChatTable
          S3_BUCKET_NAME: !Ref RagChatPromptImagesBucket
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - '*'
          AllowMethods:
            - '*'
          AllowCredentials: false

  RagChatGetChatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-get-chats-function"
      CodeUri: functions/rag-get-chats/
      Handler: app.lambda_handler
      Runtime: python3.13
      Role: !GetAtt IamStack.Outputs.RagChatLambdaGetChatRoleArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref RagChatTable
      Events:
        GetChats:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /chats
            Method: GET

  RagChatSearchChatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-search-chats-function"
      CodeUri: functions/search-chats/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaGetChatRoleArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref RagChatTable
      Events:
        GETSearch:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /search
            Method: GET

  RagChatSseStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-sse-stream-function"
      CodeUri: functions/rag-sse-stream/
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt IamStack.Outputs.RagChatLambdaGenerateRoleArn
      Environment:
        Variables:
          BEDROCK_AWS_REGION: us-west-2
          DYNAMODB_TABLE_NAME: !Ref RagChatTable
          KB_AWS_REGION: ap-northeast-1
          KNOWLEDGE_BASE_ID: MYT87G8AIP
          S3_BUCKET_NAME: !Ref RagChatPromptImagesBucket
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - '*'
          AllowMethods:
            - '*'
          AllowCredentials: false

  RagChatGetChatDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-ragchat-get-chat-detail-function"
      CodeUri: functions/rag-get-chat-detail/
      Handler: app.lambda_handler
      Runtime: python3.13
      Role: !GetAtt IamStack.Outputs.RagChatLambdaGetChatRoleArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref RagChatTable
      Events:
        GetChatDetail:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /chats/{chatId}
            Method: GET

        DeleteChatDetail:
          Type: HttpApi
          Properties:
            ApiId: !Ref RagChatHttpApi
            Path: /chats/{chatId}
            Method: DELETE
            
  # 画像プロンプト用S3バケット
  RagChatPromptImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-ragchat-prompt-images-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: ragchat-app
        - Key: ManagedBy
          Value: sam
        - Key: Environment
          Value: !Ref Environment
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "GET"
              - "PUT"
              - "POST"
              - "DELETE"
              - "HEAD"
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "ETag"
            MaxAge: 3000


  # フロントエンド用S3バケット
  RagChatFrontBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-ragchat-frontend-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: ragchat-app
        - Key: ManagedBy
          Value: sam
        - Key: Environment
          Value: !Ref Environment
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true

  # CloudFrontディストリビューション用OAC
  RagChatFrontOAI:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${Environment}-ragchat-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # S3バケットポリシー（CloudFrontからのアクセスのみ許可）
  RagChatFrontBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RagChatFrontBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${RagChatFrontBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${RagChatDistribution}"


  # CloudFrontディストリビューション
  RagChatDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "${Environment}-ragchat distribution"
        Aliases: !If 
          - HasCertificate
          - [!Ref DomainName]
          - !Ref AWS::NoValue
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate: !If
          - HasCertificate
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt RagChatFrontBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref RagChatFrontOAI
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd  # Managed-CORS-With-Preflight
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          
  # DynamoDB
  RagChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-ragchat-table"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ragchat-app
        - Key: ManagedBy
          Value: sam
        - Key: Environment
          Value: !Ref Environment

  # Cognito User Pool
  RagChatUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${Environment}-ragchat-user-pool"
      UserPoolTags:
        Project: ragchat-app
        ManagedBy: sam
        Environment: !Ref Environment
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true

  # Cognito User Pool Client
  RagChatUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${Environment}-ragchat-client"
      UserPoolId: !Ref RagChatUserPool
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 14
      PreventUserExistenceErrors: ENABLED 
      TokenValidityUnits:
        AccessToken: days
        IdToken: days
        RefreshToken: days

Outputs:
  # Cognito関連
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref RagChatUserPool
    Export:
      Name: !Sub "${AWS::StackName}-CognitoUserPoolId"

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref RagChatUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-CognitoUserPoolClientId"

  # API Gateway関連
  ApiGatewayHttpApiUrl:
    Description: API Gateway HTTP API URL
    Value: !Sub "https://${RagChatHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayHttpApiUrl"

  # Lambda Function URL関連
  RagChatGenerateImageFunctionUrl:
    Description: RAG Generate Image Function URL
    Value: !GetAtt RagChatGenerateImageFunctionUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-RagChatGenerateImageFunctionUrl"

  RagChatSseStreamFunctionUrl:
    Description: RAG SSE Stream Function URL
    Value: !GetAtt RagChatSseStreamFunctionUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-RagChatSseStreamFunctionUrl"